// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: computer.proto

// Protobuf Java Version: 3.25.1
package com.classroomsystem;

public final class ComputerProto {
  private ComputerProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface ToggleComputersRequestOrBuilder extends
      // @@protoc_insertion_point(interface_extends:classroom_system.control.ToggleComputersRequest)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <pre>
     * true表示开机，false表示关机
     * </pre>
     *
     * <code>bool power_on = 1;</code>
     * @return The powerOn.
     */
    boolean getPowerOn();
  }
  /**
   * <pre>
   * 开关机请求与响应消息
   * </pre>
   *
   * Protobuf type {@code classroom_system.control.ToggleComputersRequest}
   */
  public static final class ToggleComputersRequest extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:classroom_system.control.ToggleComputersRequest)
      ToggleComputersRequestOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use ToggleComputersRequest.newBuilder() to construct.
    private ToggleComputersRequest(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private ToggleComputersRequest() {
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new ToggleComputersRequest();
    }

    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.classroomsystem.ComputerProto.internal_static_classroom_system_control_ToggleComputersRequest_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.classroomsystem.ComputerProto.internal_static_classroom_system_control_ToggleComputersRequest_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.classroomsystem.ComputerProto.ToggleComputersRequest.class, com.classroomsystem.ComputerProto.ToggleComputersRequest.Builder.class);
    }

    public static final int POWER_ON_FIELD_NUMBER = 1;
    private boolean powerOn_ = false;
    /**
     * <pre>
     * true表示开机，false表示关机
     * </pre>
     *
     * <code>bool power_on = 1;</code>
     * @return The powerOn.
     */
    @java.lang.Override
    public boolean getPowerOn() {
      return powerOn_;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (powerOn_ != false) {
        output.writeBool(1, powerOn_);
      }
      getUnknownFields().writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (powerOn_ != false) {
        size += com.google.protobuf.CodedOutputStream
          .computeBoolSize(1, powerOn_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.classroomsystem.ComputerProto.ToggleComputersRequest)) {
        return super.equals(obj);
      }
      com.classroomsystem.ComputerProto.ToggleComputersRequest other = (com.classroomsystem.ComputerProto.ToggleComputersRequest) obj;

      if (getPowerOn()
          != other.getPowerOn()) return false;
      if (!getUnknownFields().equals(other.getUnknownFields())) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + POWER_ON_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
          getPowerOn());
      hash = (29 * hash) + getUnknownFields().hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.classroomsystem.ComputerProto.ToggleComputersRequest parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.classroomsystem.ComputerProto.ToggleComputersRequest parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.classroomsystem.ComputerProto.ToggleComputersRequest parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.classroomsystem.ComputerProto.ToggleComputersRequest parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.classroomsystem.ComputerProto.ToggleComputersRequest parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.classroomsystem.ComputerProto.ToggleComputersRequest parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.classroomsystem.ComputerProto.ToggleComputersRequest parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.classroomsystem.ComputerProto.ToggleComputersRequest parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public static com.classroomsystem.ComputerProto.ToggleComputersRequest parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }

    public static com.classroomsystem.ComputerProto.ToggleComputersRequest parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.classroomsystem.ComputerProto.ToggleComputersRequest parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.classroomsystem.ComputerProto.ToggleComputersRequest parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.classroomsystem.ComputerProto.ToggleComputersRequest prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * <pre>
     * 开关机请求与响应消息
     * </pre>
     *
     * Protobuf type {@code classroom_system.control.ToggleComputersRequest}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:classroom_system.control.ToggleComputersRequest)
        com.classroomsystem.ComputerProto.ToggleComputersRequestOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.classroomsystem.ComputerProto.internal_static_classroom_system_control_ToggleComputersRequest_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.classroomsystem.ComputerProto.internal_static_classroom_system_control_ToggleComputersRequest_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.classroomsystem.ComputerProto.ToggleComputersRequest.class, com.classroomsystem.ComputerProto.ToggleComputersRequest.Builder.class);
      }

      // Construct using com.classroomsystem.ComputerProto.ToggleComputersRequest.newBuilder()
      private Builder() {

      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);

      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        bitField0_ = 0;
        powerOn_ = false;
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.classroomsystem.ComputerProto.internal_static_classroom_system_control_ToggleComputersRequest_descriptor;
      }

      @java.lang.Override
      public com.classroomsystem.ComputerProto.ToggleComputersRequest getDefaultInstanceForType() {
        return com.classroomsystem.ComputerProto.ToggleComputersRequest.getDefaultInstance();
      }

      @java.lang.Override
      public com.classroomsystem.ComputerProto.ToggleComputersRequest build() {
        com.classroomsystem.ComputerProto.ToggleComputersRequest result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public com.classroomsystem.ComputerProto.ToggleComputersRequest buildPartial() {
        com.classroomsystem.ComputerProto.ToggleComputersRequest result = new com.classroomsystem.ComputerProto.ToggleComputersRequest(this);
        if (bitField0_ != 0) { buildPartial0(result); }
        onBuilt();
        return result;
      }

      private void buildPartial0(com.classroomsystem.ComputerProto.ToggleComputersRequest result) {
        int from_bitField0_ = bitField0_;
        if (((from_bitField0_ & 0x00000001) != 0)) {
          result.powerOn_ = powerOn_;
        }
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.classroomsystem.ComputerProto.ToggleComputersRequest) {
          return mergeFrom((com.classroomsystem.ComputerProto.ToggleComputersRequest)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.classroomsystem.ComputerProto.ToggleComputersRequest other) {
        if (other == com.classroomsystem.ComputerProto.ToggleComputersRequest.getDefaultInstance()) return this;
        if (other.getPowerOn() != false) {
          setPowerOn(other.getPowerOn());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        if (extensionRegistry == null) {
          throw new java.lang.NullPointerException();
        }
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              case 8: {
                powerOn_ = input.readBool();
                bitField0_ |= 0x00000001;
                break;
              } // case 8
              default: {
                if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                  done = true; // was an endgroup tag
                }
                break;
              } // default:
            } // switch (tag)
          } // while (!done)
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.unwrapIOException();
        } finally {
          onChanged();
        } // finally
        return this;
      }
      private int bitField0_;

      private boolean powerOn_ ;
      /**
       * <pre>
       * true表示开机，false表示关机
       * </pre>
       *
       * <code>bool power_on = 1;</code>
       * @return The powerOn.
       */
      @java.lang.Override
      public boolean getPowerOn() {
        return powerOn_;
      }
      /**
       * <pre>
       * true表示开机，false表示关机
       * </pre>
       *
       * <code>bool power_on = 1;</code>
       * @param value The powerOn to set.
       * @return This builder for chaining.
       */
      public Builder setPowerOn(boolean value) {

        powerOn_ = value;
        bitField0_ |= 0x00000001;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * true表示开机，false表示关机
       * </pre>
       *
       * <code>bool power_on = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearPowerOn() {
        bitField0_ = (bitField0_ & ~0x00000001);
        powerOn_ = false;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:classroom_system.control.ToggleComputersRequest)
    }

    // @@protoc_insertion_point(class_scope:classroom_system.control.ToggleComputersRequest)
    private static final com.classroomsystem.ComputerProto.ToggleComputersRequest DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.classroomsystem.ComputerProto.ToggleComputersRequest();
    }

    public static com.classroomsystem.ComputerProto.ToggleComputersRequest getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<ToggleComputersRequest>
        PARSER = new com.google.protobuf.AbstractParser<ToggleComputersRequest>() {
      @java.lang.Override
      public ToggleComputersRequest parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        Builder builder = newBuilder();
        try {
          builder.mergeFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(builder.buildPartial());
        } catch (com.google.protobuf.UninitializedMessageException e) {
          throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(e)
              .setUnfinishedMessage(builder.buildPartial());
        }
        return builder.buildPartial();
      }
    };

    public static com.google.protobuf.Parser<ToggleComputersRequest> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<ToggleComputersRequest> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public com.classroomsystem.ComputerProto.ToggleComputersRequest getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface ToggleComputersResponseOrBuilder extends
      // @@protoc_insertion_point(interface_extends:classroom_system.control.ToggleComputersResponse)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <pre>
     * 表示操作是否成功完成
     * </pre>
     *
     * <code>bool success = 1;</code>
     * @return The success.
     */
    boolean getSuccess();

    /**
     * <pre>
     * 如果操作失败，提供有关失败原因的详细信息
     * </pre>
     *
     * <code>string message = 2;</code>
     * @return The message.
     */
    java.lang.String getMessage();
    /**
     * <pre>
     * 如果操作失败，提供有关失败原因的详细信息
     * </pre>
     *
     * <code>string message = 2;</code>
     * @return The bytes for message.
     */
    com.google.protobuf.ByteString
        getMessageBytes();
  }
  /**
   * Protobuf type {@code classroom_system.control.ToggleComputersResponse}
   */
  public static final class ToggleComputersResponse extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:classroom_system.control.ToggleComputersResponse)
      ToggleComputersResponseOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use ToggleComputersResponse.newBuilder() to construct.
    private ToggleComputersResponse(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private ToggleComputersResponse() {
      message_ = "";
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new ToggleComputersResponse();
    }

    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.classroomsystem.ComputerProto.internal_static_classroom_system_control_ToggleComputersResponse_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.classroomsystem.ComputerProto.internal_static_classroom_system_control_ToggleComputersResponse_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.classroomsystem.ComputerProto.ToggleComputersResponse.class, com.classroomsystem.ComputerProto.ToggleComputersResponse.Builder.class);
    }

    public static final int SUCCESS_FIELD_NUMBER = 1;
    private boolean success_ = false;
    /**
     * <pre>
     * 表示操作是否成功完成
     * </pre>
     *
     * <code>bool success = 1;</code>
     * @return The success.
     */
    @java.lang.Override
    public boolean getSuccess() {
      return success_;
    }

    public static final int MESSAGE_FIELD_NUMBER = 2;
    @SuppressWarnings("serial")
    private volatile java.lang.Object message_ = "";
    /**
     * <pre>
     * 如果操作失败，提供有关失败原因的详细信息
     * </pre>
     *
     * <code>string message = 2;</code>
     * @return The message.
     */
    @java.lang.Override
    public java.lang.String getMessage() {
      java.lang.Object ref = message_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        message_ = s;
        return s;
      }
    }
    /**
     * <pre>
     * 如果操作失败，提供有关失败原因的详细信息
     * </pre>
     *
     * <code>string message = 2;</code>
     * @return The bytes for message.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getMessageBytes() {
      java.lang.Object ref = message_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        message_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (success_ != false) {
        output.writeBool(1, success_);
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(message_)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, message_);
      }
      getUnknownFields().writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (success_ != false) {
        size += com.google.protobuf.CodedOutputStream
          .computeBoolSize(1, success_);
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(message_)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, message_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.classroomsystem.ComputerProto.ToggleComputersResponse)) {
        return super.equals(obj);
      }
      com.classroomsystem.ComputerProto.ToggleComputersResponse other = (com.classroomsystem.ComputerProto.ToggleComputersResponse) obj;

      if (getSuccess()
          != other.getSuccess()) return false;
      if (!getMessage()
          .equals(other.getMessage())) return false;
      if (!getUnknownFields().equals(other.getUnknownFields())) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + SUCCESS_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
          getSuccess());
      hash = (37 * hash) + MESSAGE_FIELD_NUMBER;
      hash = (53 * hash) + getMessage().hashCode();
      hash = (29 * hash) + getUnknownFields().hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.classroomsystem.ComputerProto.ToggleComputersResponse parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.classroomsystem.ComputerProto.ToggleComputersResponse parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.classroomsystem.ComputerProto.ToggleComputersResponse parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.classroomsystem.ComputerProto.ToggleComputersResponse parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.classroomsystem.ComputerProto.ToggleComputersResponse parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.classroomsystem.ComputerProto.ToggleComputersResponse parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.classroomsystem.ComputerProto.ToggleComputersResponse parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.classroomsystem.ComputerProto.ToggleComputersResponse parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public static com.classroomsystem.ComputerProto.ToggleComputersResponse parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }

    public static com.classroomsystem.ComputerProto.ToggleComputersResponse parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.classroomsystem.ComputerProto.ToggleComputersResponse parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.classroomsystem.ComputerProto.ToggleComputersResponse parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.classroomsystem.ComputerProto.ToggleComputersResponse prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code classroom_system.control.ToggleComputersResponse}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:classroom_system.control.ToggleComputersResponse)
        com.classroomsystem.ComputerProto.ToggleComputersResponseOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.classroomsystem.ComputerProto.internal_static_classroom_system_control_ToggleComputersResponse_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.classroomsystem.ComputerProto.internal_static_classroom_system_control_ToggleComputersResponse_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.classroomsystem.ComputerProto.ToggleComputersResponse.class, com.classroomsystem.ComputerProto.ToggleComputersResponse.Builder.class);
      }

      // Construct using com.classroomsystem.ComputerProto.ToggleComputersResponse.newBuilder()
      private Builder() {

      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);

      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        bitField0_ = 0;
        success_ = false;
        message_ = "";
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.classroomsystem.ComputerProto.internal_static_classroom_system_control_ToggleComputersResponse_descriptor;
      }

      @java.lang.Override
      public com.classroomsystem.ComputerProto.ToggleComputersResponse getDefaultInstanceForType() {
        return com.classroomsystem.ComputerProto.ToggleComputersResponse.getDefaultInstance();
      }

      @java.lang.Override
      public com.classroomsystem.ComputerProto.ToggleComputersResponse build() {
        com.classroomsystem.ComputerProto.ToggleComputersResponse result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public com.classroomsystem.ComputerProto.ToggleComputersResponse buildPartial() {
        com.classroomsystem.ComputerProto.ToggleComputersResponse result = new com.classroomsystem.ComputerProto.ToggleComputersResponse(this);
        if (bitField0_ != 0) { buildPartial0(result); }
        onBuilt();
        return result;
      }

      private void buildPartial0(com.classroomsystem.ComputerProto.ToggleComputersResponse result) {
        int from_bitField0_ = bitField0_;
        if (((from_bitField0_ & 0x00000001) != 0)) {
          result.success_ = success_;
        }
        if (((from_bitField0_ & 0x00000002) != 0)) {
          result.message_ = message_;
        }
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.classroomsystem.ComputerProto.ToggleComputersResponse) {
          return mergeFrom((com.classroomsystem.ComputerProto.ToggleComputersResponse)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.classroomsystem.ComputerProto.ToggleComputersResponse other) {
        if (other == com.classroomsystem.ComputerProto.ToggleComputersResponse.getDefaultInstance()) return this;
        if (other.getSuccess() != false) {
          setSuccess(other.getSuccess());
        }
        if (!other.getMessage().isEmpty()) {
          message_ = other.message_;
          bitField0_ |= 0x00000002;
          onChanged();
        }
        this.mergeUnknownFields(other.getUnknownFields());
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        if (extensionRegistry == null) {
          throw new java.lang.NullPointerException();
        }
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              case 8: {
                success_ = input.readBool();
                bitField0_ |= 0x00000001;
                break;
              } // case 8
              case 18: {
                message_ = input.readStringRequireUtf8();
                bitField0_ |= 0x00000002;
                break;
              } // case 18
              default: {
                if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                  done = true; // was an endgroup tag
                }
                break;
              } // default:
            } // switch (tag)
          } // while (!done)
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.unwrapIOException();
        } finally {
          onChanged();
        } // finally
        return this;
      }
      private int bitField0_;

      private boolean success_ ;
      /**
       * <pre>
       * 表示操作是否成功完成
       * </pre>
       *
       * <code>bool success = 1;</code>
       * @return The success.
       */
      @java.lang.Override
      public boolean getSuccess() {
        return success_;
      }
      /**
       * <pre>
       * 表示操作是否成功完成
       * </pre>
       *
       * <code>bool success = 1;</code>
       * @param value The success to set.
       * @return This builder for chaining.
       */
      public Builder setSuccess(boolean value) {

        success_ = value;
        bitField0_ |= 0x00000001;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 表示操作是否成功完成
       * </pre>
       *
       * <code>bool success = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearSuccess() {
        bitField0_ = (bitField0_ & ~0x00000001);
        success_ = false;
        onChanged();
        return this;
      }

      private java.lang.Object message_ = "";
      /**
       * <pre>
       * 如果操作失败，提供有关失败原因的详细信息
       * </pre>
       *
       * <code>string message = 2;</code>
       * @return The message.
       */
      public java.lang.String getMessage() {
        java.lang.Object ref = message_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          message_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <pre>
       * 如果操作失败，提供有关失败原因的详细信息
       * </pre>
       *
       * <code>string message = 2;</code>
       * @return The bytes for message.
       */
      public com.google.protobuf.ByteString
          getMessageBytes() {
        java.lang.Object ref = message_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          message_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       * 如果操作失败，提供有关失败原因的详细信息
       * </pre>
       *
       * <code>string message = 2;</code>
       * @param value The message to set.
       * @return This builder for chaining.
       */
      public Builder setMessage(
          java.lang.String value) {
        if (value == null) { throw new NullPointerException(); }
        message_ = value;
        bitField0_ |= 0x00000002;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 如果操作失败，提供有关失败原因的详细信息
       * </pre>
       *
       * <code>string message = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearMessage() {
        message_ = getDefaultInstance().getMessage();
        bitField0_ = (bitField0_ & ~0x00000002);
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 如果操作失败，提供有关失败原因的详细信息
       * </pre>
       *
       * <code>string message = 2;</code>
       * @param value The bytes for message to set.
       * @return This builder for chaining.
       */
      public Builder setMessageBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) { throw new NullPointerException(); }
        checkByteStringIsUtf8(value);
        message_ = value;
        bitField0_ |= 0x00000002;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:classroom_system.control.ToggleComputersResponse)
    }

    // @@protoc_insertion_point(class_scope:classroom_system.control.ToggleComputersResponse)
    private static final com.classroomsystem.ComputerProto.ToggleComputersResponse DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.classroomsystem.ComputerProto.ToggleComputersResponse();
    }

    public static com.classroomsystem.ComputerProto.ToggleComputersResponse getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<ToggleComputersResponse>
        PARSER = new com.google.protobuf.AbstractParser<ToggleComputersResponse>() {
      @java.lang.Override
      public ToggleComputersResponse parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        Builder builder = newBuilder();
        try {
          builder.mergeFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(builder.buildPartial());
        } catch (com.google.protobuf.UninitializedMessageException e) {
          throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(e)
              .setUnfinishedMessage(builder.buildPartial());
        }
        return builder.buildPartial();
      }
    };

    public static com.google.protobuf.Parser<ToggleComputersResponse> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<ToggleComputersResponse> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public com.classroomsystem.ComputerProto.ToggleComputersResponse getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface EmptyOrBuilder extends
      // @@protoc_insertion_point(interface_extends:classroom_system.control.Empty)
      com.google.protobuf.MessageOrBuilder {
  }
  /**
   * <pre>
   * 空消息，用于不需要参数的RPC调用
   * </pre>
   *
   * Protobuf type {@code classroom_system.control.Empty}
   */
  public static final class Empty extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:classroom_system.control.Empty)
      EmptyOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use Empty.newBuilder() to construct.
    private Empty(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private Empty() {
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new Empty();
    }

    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.classroomsystem.ComputerProto.internal_static_classroom_system_control_Empty_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.classroomsystem.ComputerProto.internal_static_classroom_system_control_Empty_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.classroomsystem.ComputerProto.Empty.class, com.classroomsystem.ComputerProto.Empty.Builder.class);
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getUnknownFields().writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      size += getUnknownFields().getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.classroomsystem.ComputerProto.Empty)) {
        return super.equals(obj);
      }
      com.classroomsystem.ComputerProto.Empty other = (com.classroomsystem.ComputerProto.Empty) obj;

      if (!getUnknownFields().equals(other.getUnknownFields())) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (29 * hash) + getUnknownFields().hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.classroomsystem.ComputerProto.Empty parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.classroomsystem.ComputerProto.Empty parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.classroomsystem.ComputerProto.Empty parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.classroomsystem.ComputerProto.Empty parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.classroomsystem.ComputerProto.Empty parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.classroomsystem.ComputerProto.Empty parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.classroomsystem.ComputerProto.Empty parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.classroomsystem.ComputerProto.Empty parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public static com.classroomsystem.ComputerProto.Empty parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }

    public static com.classroomsystem.ComputerProto.Empty parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.classroomsystem.ComputerProto.Empty parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.classroomsystem.ComputerProto.Empty parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.classroomsystem.ComputerProto.Empty prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * <pre>
     * 空消息，用于不需要参数的RPC调用
     * </pre>
     *
     * Protobuf type {@code classroom_system.control.Empty}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:classroom_system.control.Empty)
        com.classroomsystem.ComputerProto.EmptyOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.classroomsystem.ComputerProto.internal_static_classroom_system_control_Empty_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.classroomsystem.ComputerProto.internal_static_classroom_system_control_Empty_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.classroomsystem.ComputerProto.Empty.class, com.classroomsystem.ComputerProto.Empty.Builder.class);
      }

      // Construct using com.classroomsystem.ComputerProto.Empty.newBuilder()
      private Builder() {

      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);

      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.classroomsystem.ComputerProto.internal_static_classroom_system_control_Empty_descriptor;
      }

      @java.lang.Override
      public com.classroomsystem.ComputerProto.Empty getDefaultInstanceForType() {
        return com.classroomsystem.ComputerProto.Empty.getDefaultInstance();
      }

      @java.lang.Override
      public com.classroomsystem.ComputerProto.Empty build() {
        com.classroomsystem.ComputerProto.Empty result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public com.classroomsystem.ComputerProto.Empty buildPartial() {
        com.classroomsystem.ComputerProto.Empty result = new com.classroomsystem.ComputerProto.Empty(this);
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.classroomsystem.ComputerProto.Empty) {
          return mergeFrom((com.classroomsystem.ComputerProto.Empty)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.classroomsystem.ComputerProto.Empty other) {
        if (other == com.classroomsystem.ComputerProto.Empty.getDefaultInstance()) return this;
        this.mergeUnknownFields(other.getUnknownFields());
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        if (extensionRegistry == null) {
          throw new java.lang.NullPointerException();
        }
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              default: {
                if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                  done = true; // was an endgroup tag
                }
                break;
              } // default:
            } // switch (tag)
          } // while (!done)
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.unwrapIOException();
        } finally {
          onChanged();
        } // finally
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:classroom_system.control.Empty)
    }

    // @@protoc_insertion_point(class_scope:classroom_system.control.Empty)
    private static final com.classroomsystem.ComputerProto.Empty DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.classroomsystem.ComputerProto.Empty();
    }

    public static com.classroomsystem.ComputerProto.Empty getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<Empty>
        PARSER = new com.google.protobuf.AbstractParser<Empty>() {
      @java.lang.Override
      public Empty parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        Builder builder = newBuilder();
        try {
          builder.mergeFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(builder.buildPartial());
        } catch (com.google.protobuf.UninitializedMessageException e) {
          throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(e)
              .setUnfinishedMessage(builder.buildPartial());
        }
        return builder.buildPartial();
      }
    };

    public static com.google.protobuf.Parser<Empty> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<Empty> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public com.classroomsystem.ComputerProto.Empty getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface ComputerStatusResponseOrBuilder extends
      // @@protoc_insertion_point(interface_extends:classroom_system.control.ComputerStatusResponse)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <pre>
     * 表示电脑是否开启
     * </pre>
     *
     * <code>bool is_on = 1;</code>
     * @return The isOn.
     */
    boolean getIsOn();

    /**
     * <pre>
     * 提供额外的状态信息
     * </pre>
     *
     * <code>string status_info = 2;</code>
     * @return The statusInfo.
     */
    java.lang.String getStatusInfo();
    /**
     * <pre>
     * 提供额外的状态信息
     * </pre>
     *
     * <code>string status_info = 2;</code>
     * @return The bytes for statusInfo.
     */
    com.google.protobuf.ByteString
        getStatusInfoBytes();
  }
  /**
   * <pre>
   * 电脑状态响应，用于服务端流
   * </pre>
   *
   * Protobuf type {@code classroom_system.control.ComputerStatusResponse}
   */
  public static final class ComputerStatusResponse extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:classroom_system.control.ComputerStatusResponse)
      ComputerStatusResponseOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use ComputerStatusResponse.newBuilder() to construct.
    private ComputerStatusResponse(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private ComputerStatusResponse() {
      statusInfo_ = "";
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new ComputerStatusResponse();
    }

    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.classroomsystem.ComputerProto.internal_static_classroom_system_control_ComputerStatusResponse_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.classroomsystem.ComputerProto.internal_static_classroom_system_control_ComputerStatusResponse_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.classroomsystem.ComputerProto.ComputerStatusResponse.class, com.classroomsystem.ComputerProto.ComputerStatusResponse.Builder.class);
    }

    public static final int IS_ON_FIELD_NUMBER = 1;
    private boolean isOn_ = false;
    /**
     * <pre>
     * 表示电脑是否开启
     * </pre>
     *
     * <code>bool is_on = 1;</code>
     * @return The isOn.
     */
    @java.lang.Override
    public boolean getIsOn() {
      return isOn_;
    }

    public static final int STATUS_INFO_FIELD_NUMBER = 2;
    @SuppressWarnings("serial")
    private volatile java.lang.Object statusInfo_ = "";
    /**
     * <pre>
     * 提供额外的状态信息
     * </pre>
     *
     * <code>string status_info = 2;</code>
     * @return The statusInfo.
     */
    @java.lang.Override
    public java.lang.String getStatusInfo() {
      java.lang.Object ref = statusInfo_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        statusInfo_ = s;
        return s;
      }
    }
    /**
     * <pre>
     * 提供额外的状态信息
     * </pre>
     *
     * <code>string status_info = 2;</code>
     * @return The bytes for statusInfo.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getStatusInfoBytes() {
      java.lang.Object ref = statusInfo_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        statusInfo_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (isOn_ != false) {
        output.writeBool(1, isOn_);
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(statusInfo_)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, statusInfo_);
      }
      getUnknownFields().writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (isOn_ != false) {
        size += com.google.protobuf.CodedOutputStream
          .computeBoolSize(1, isOn_);
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(statusInfo_)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, statusInfo_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.classroomsystem.ComputerProto.ComputerStatusResponse)) {
        return super.equals(obj);
      }
      com.classroomsystem.ComputerProto.ComputerStatusResponse other = (com.classroomsystem.ComputerProto.ComputerStatusResponse) obj;

      if (getIsOn()
          != other.getIsOn()) return false;
      if (!getStatusInfo()
          .equals(other.getStatusInfo())) return false;
      if (!getUnknownFields().equals(other.getUnknownFields())) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + IS_ON_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
          getIsOn());
      hash = (37 * hash) + STATUS_INFO_FIELD_NUMBER;
      hash = (53 * hash) + getStatusInfo().hashCode();
      hash = (29 * hash) + getUnknownFields().hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.classroomsystem.ComputerProto.ComputerStatusResponse parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.classroomsystem.ComputerProto.ComputerStatusResponse parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.classroomsystem.ComputerProto.ComputerStatusResponse parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.classroomsystem.ComputerProto.ComputerStatusResponse parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.classroomsystem.ComputerProto.ComputerStatusResponse parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.classroomsystem.ComputerProto.ComputerStatusResponse parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.classroomsystem.ComputerProto.ComputerStatusResponse parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.classroomsystem.ComputerProto.ComputerStatusResponse parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public static com.classroomsystem.ComputerProto.ComputerStatusResponse parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }

    public static com.classroomsystem.ComputerProto.ComputerStatusResponse parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.classroomsystem.ComputerProto.ComputerStatusResponse parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.classroomsystem.ComputerProto.ComputerStatusResponse parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.classroomsystem.ComputerProto.ComputerStatusResponse prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * <pre>
     * 电脑状态响应，用于服务端流
     * </pre>
     *
     * Protobuf type {@code classroom_system.control.ComputerStatusResponse}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:classroom_system.control.ComputerStatusResponse)
        com.classroomsystem.ComputerProto.ComputerStatusResponseOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.classroomsystem.ComputerProto.internal_static_classroom_system_control_ComputerStatusResponse_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.classroomsystem.ComputerProto.internal_static_classroom_system_control_ComputerStatusResponse_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.classroomsystem.ComputerProto.ComputerStatusResponse.class, com.classroomsystem.ComputerProto.ComputerStatusResponse.Builder.class);
      }

      // Construct using com.classroomsystem.ComputerProto.ComputerStatusResponse.newBuilder()
      private Builder() {

      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);

      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        bitField0_ = 0;
        isOn_ = false;
        statusInfo_ = "";
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.classroomsystem.ComputerProto.internal_static_classroom_system_control_ComputerStatusResponse_descriptor;
      }

      @java.lang.Override
      public com.classroomsystem.ComputerProto.ComputerStatusResponse getDefaultInstanceForType() {
        return com.classroomsystem.ComputerProto.ComputerStatusResponse.getDefaultInstance();
      }

      @java.lang.Override
      public com.classroomsystem.ComputerProto.ComputerStatusResponse build() {
        com.classroomsystem.ComputerProto.ComputerStatusResponse result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public com.classroomsystem.ComputerProto.ComputerStatusResponse buildPartial() {
        com.classroomsystem.ComputerProto.ComputerStatusResponse result = new com.classroomsystem.ComputerProto.ComputerStatusResponse(this);
        if (bitField0_ != 0) { buildPartial0(result); }
        onBuilt();
        return result;
      }

      private void buildPartial0(com.classroomsystem.ComputerProto.ComputerStatusResponse result) {
        int from_bitField0_ = bitField0_;
        if (((from_bitField0_ & 0x00000001) != 0)) {
          result.isOn_ = isOn_;
        }
        if (((from_bitField0_ & 0x00000002) != 0)) {
          result.statusInfo_ = statusInfo_;
        }
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.classroomsystem.ComputerProto.ComputerStatusResponse) {
          return mergeFrom((com.classroomsystem.ComputerProto.ComputerStatusResponse)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.classroomsystem.ComputerProto.ComputerStatusResponse other) {
        if (other == com.classroomsystem.ComputerProto.ComputerStatusResponse.getDefaultInstance()) return this;
        if (other.getIsOn() != false) {
          setIsOn(other.getIsOn());
        }
        if (!other.getStatusInfo().isEmpty()) {
          statusInfo_ = other.statusInfo_;
          bitField0_ |= 0x00000002;
          onChanged();
        }
        this.mergeUnknownFields(other.getUnknownFields());
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        if (extensionRegistry == null) {
          throw new java.lang.NullPointerException();
        }
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              case 8: {
                isOn_ = input.readBool();
                bitField0_ |= 0x00000001;
                break;
              } // case 8
              case 18: {
                statusInfo_ = input.readStringRequireUtf8();
                bitField0_ |= 0x00000002;
                break;
              } // case 18
              default: {
                if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                  done = true; // was an endgroup tag
                }
                break;
              } // default:
            } // switch (tag)
          } // while (!done)
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.unwrapIOException();
        } finally {
          onChanged();
        } // finally
        return this;
      }
      private int bitField0_;

      private boolean isOn_ ;
      /**
       * <pre>
       * 表示电脑是否开启
       * </pre>
       *
       * <code>bool is_on = 1;</code>
       * @return The isOn.
       */
      @java.lang.Override
      public boolean getIsOn() {
        return isOn_;
      }
      /**
       * <pre>
       * 表示电脑是否开启
       * </pre>
       *
       * <code>bool is_on = 1;</code>
       * @param value The isOn to set.
       * @return This builder for chaining.
       */
      public Builder setIsOn(boolean value) {

        isOn_ = value;
        bitField0_ |= 0x00000001;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 表示电脑是否开启
       * </pre>
       *
       * <code>bool is_on = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearIsOn() {
        bitField0_ = (bitField0_ & ~0x00000001);
        isOn_ = false;
        onChanged();
        return this;
      }

      private java.lang.Object statusInfo_ = "";
      /**
       * <pre>
       * 提供额外的状态信息
       * </pre>
       *
       * <code>string status_info = 2;</code>
       * @return The statusInfo.
       */
      public java.lang.String getStatusInfo() {
        java.lang.Object ref = statusInfo_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          statusInfo_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <pre>
       * 提供额外的状态信息
       * </pre>
       *
       * <code>string status_info = 2;</code>
       * @return The bytes for statusInfo.
       */
      public com.google.protobuf.ByteString
          getStatusInfoBytes() {
        java.lang.Object ref = statusInfo_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          statusInfo_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       * 提供额外的状态信息
       * </pre>
       *
       * <code>string status_info = 2;</code>
       * @param value The statusInfo to set.
       * @return This builder for chaining.
       */
      public Builder setStatusInfo(
          java.lang.String value) {
        if (value == null) { throw new NullPointerException(); }
        statusInfo_ = value;
        bitField0_ |= 0x00000002;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 提供额外的状态信息
       * </pre>
       *
       * <code>string status_info = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearStatusInfo() {
        statusInfo_ = getDefaultInstance().getStatusInfo();
        bitField0_ = (bitField0_ & ~0x00000002);
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 提供额外的状态信息
       * </pre>
       *
       * <code>string status_info = 2;</code>
       * @param value The bytes for statusInfo to set.
       * @return This builder for chaining.
       */
      public Builder setStatusInfoBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) { throw new NullPointerException(); }
        checkByteStringIsUtf8(value);
        statusInfo_ = value;
        bitField0_ |= 0x00000002;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:classroom_system.control.ComputerStatusResponse)
    }

    // @@protoc_insertion_point(class_scope:classroom_system.control.ComputerStatusResponse)
    private static final com.classroomsystem.ComputerProto.ComputerStatusResponse DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.classroomsystem.ComputerProto.ComputerStatusResponse();
    }

    public static com.classroomsystem.ComputerProto.ComputerStatusResponse getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<ComputerStatusResponse>
        PARSER = new com.google.protobuf.AbstractParser<ComputerStatusResponse>() {
      @java.lang.Override
      public ComputerStatusResponse parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        Builder builder = newBuilder();
        try {
          builder.mergeFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(builder.buildPartial());
        } catch (com.google.protobuf.UninitializedMessageException e) {
          throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(e)
              .setUnfinishedMessage(builder.buildPartial());
        }
        return builder.buildPartial();
      }
    };

    public static com.google.protobuf.Parser<ComputerStatusResponse> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<ComputerStatusResponse> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public com.classroomsystem.ComputerProto.ComputerStatusResponse getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_classroom_system_control_ToggleComputersRequest_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_classroom_system_control_ToggleComputersRequest_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_classroom_system_control_ToggleComputersResponse_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_classroom_system_control_ToggleComputersResponse_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_classroom_system_control_Empty_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_classroom_system_control_Empty_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_classroom_system_control_ComputerStatusResponse_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_classroom_system_control_ComputerStatusResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\016computer.proto\022\030classroom_system.contr" +
      "ol\"*\n\026ToggleComputersRequest\022\020\n\010power_on" +
      "\030\001 \001(\010\";\n\027ToggleComputersResponse\022\017\n\007suc" +
      "cess\030\001 \001(\010\022\017\n\007message\030\002 \001(\t\"\007\n\005Empty\"<\n\026" +
      "ComputerStatusResponse\022\r\n\005is_on\030\001 \001(\010\022\023\n" +
      "\013status_info\030\002 \001(\t2\373\001\n\026ComputerControlSe" +
      "rvice\022v\n\017ToggleComputers\0220.classroom_sys" +
      "tem.control.ToggleComputersRequest\0321.cla" +
      "ssroom_system.control.ToggleComputersRes" +
      "ponse\022i\n\020MonitorComputers\022\037.classroom_sy" +
      "stem.control.Empty\0320.classroom_system.co" +
      "ntrol.ComputerStatusResponse\"\0000\001B&\n\023com." +
      "classroomsystemB\rComputerProtoP\000b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_classroom_system_control_ToggleComputersRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_classroom_system_control_ToggleComputersRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_classroom_system_control_ToggleComputersRequest_descriptor,
        new java.lang.String[] { "PowerOn", });
    internal_static_classroom_system_control_ToggleComputersResponse_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_classroom_system_control_ToggleComputersResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_classroom_system_control_ToggleComputersResponse_descriptor,
        new java.lang.String[] { "Success", "Message", });
    internal_static_classroom_system_control_Empty_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_classroom_system_control_Empty_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_classroom_system_control_Empty_descriptor,
        new java.lang.String[] { });
    internal_static_classroom_system_control_ComputerStatusResponse_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_classroom_system_control_ComputerStatusResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_classroom_system_control_ComputerStatusResponse_descriptor,
        new java.lang.String[] { "IsOn", "StatusInfo", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
